name: learn-github-actions
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push cached on registry by docker buildx
        env:
          URI: kasano/app-c-x
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{env.URI}}:latest
          network: host
          cache-from: type=registry,ref=${{env.URI}}:buildcache
          cache-to: type=registry,ref=${{env.URI}}:buildcache,mode=max

      - name: Build and push cached on local by docker buildx
        env:
          URI: kasano/app-c-x-local
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{env.URI}}:latest
          network: host
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Build and push cached on registry by docker build
        env:
          URI: kasano/app-c
          DOCKER_BUILDKIT: 1
        run: |
          docker build --network=host \
            --target deps \
            --cache-from=${URI}:deps \
            -t ${URI}:deps \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            -f Dockerfile \
            .
          docker push ${URI}:deps

          docker build --network=host \
            --cache-from=${URI}:deps \
            --cache-from=${URI} \
            -t ${URI}:latest \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            -f Dockerfile \
            .
          docker push ${URI}:latest
      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
